// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5WaGDIbUommh5IgZpTz8nsPG6JlryZks',
    appId: '1:20721463887:web:14bb33e096a0c8d82cf03a',
    messagingSenderId: '20721463887',
    projectId: 'marketuafinal',
    authDomain: 'marketuafinal.firebaseapp.com',
    storageBucket: 'marketuafinal.firebasestorage.app',
    measurementId: 'G-4YNLL55XCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Md_8NCBuKDUamwa9RAnp29tXr-Spb8w',
    appId: '1:20721463887:android:5b995178a53c3d3f2cf03a',
    messagingSenderId: '20721463887',
    projectId: 'marketuafinal',
    storageBucket: 'marketuafinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ1U9pN0JbVj5DTUq1uwtblGdbgDjtXXc',
    appId: '1:20721463887:ios:1f1e4ceaebb8b14c2cf03a',
    messagingSenderId: '20721463887',
    projectId: 'marketuafinal',
    storageBucket: 'marketuafinal.firebasestorage.app',
    iosClientId: '20721463887-3m71thvd3nn60sj13cildqspntqvtv1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.market1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ1U9pN0JbVj5DTUq1uwtblGdbgDjtXXc',
    appId: '1:20721463887:ios:1f1e4ceaebb8b14c2cf03a',
    messagingSenderId: '20721463887',
    projectId: 'marketuafinal',
    storageBucket: 'marketuafinal.firebasestorage.app',
    iosClientId: '20721463887-3m71thvd3nn60sj13cildqspntqvtv1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.market1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5WaGDIbUommh5IgZpTz8nsPG6JlryZks',
    appId: '1:20721463887:web:63848f2095160e442cf03a',
    messagingSenderId: '20721463887',
    projectId: 'marketuafinal',
    authDomain: 'marketuafinal.firebaseapp.com',
    storageBucket: 'marketuafinal.firebasestorage.app',
    measurementId: 'G-N2085VLRTR',
  );
}
